USE [master]
GO
/****** Object:  Database [20212C_TP]    Script Date: 10/13/2021 11:34:49 PM ******/
CREATE DATABASE [20212C_TP]
GO
ALTER DATABASE [20212C_TP] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [20212C_TP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [20212C_TP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [20212C_TP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [20212C_TP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [20212C_TP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [20212C_TP] SET ARITHABORT OFF 
GO
ALTER DATABASE [20212C_TP] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [20212C_TP] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [20212C_TP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [20212C_TP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [20212C_TP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [20212C_TP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [20212C_TP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [20212C_TP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [20212C_TP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [20212C_TP] SET  DISABLE_BROKER 
GO
ALTER DATABASE [20212C_TP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [20212C_TP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [20212C_TP] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [20212C_TP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [20212C_TP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [20212C_TP] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [20212C_TP] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [20212C_TP] SET RECOVERY FULL 
GO
ALTER DATABASE [20212C_TP] SET  MULTI_USER 
GO
ALTER DATABASE [20212C_TP] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [20212C_TP] SET DB_CHAINING OFF 
GO
ALTER DATABASE [20212C_TP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [20212C_TP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [20212C_TP] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [20212C_TP] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'20212C_TP', N'ON'
GO
ALTER DATABASE [20212C_TP] SET QUERY_STORE = OFF
GO
USE [20212C_TP]
GO
/****** Object:  Table [dbo].[Calificaciones]    Script Date: 10/13/2021 11:34:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Calificaciones](
	[IdCalificacion] [int] IDENTITY(1,1) NOT NULL,
	[IdEvento] [int] NOT NULL,
	[IdComensal] [int] NOT NULL,
	[Calificacion] [int] NOT NULL,
	[Comentarios] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Calificaciones] PRIMARY KEY CLUSTERED 
(
	[IdCalificacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Eventos]    Script Date: 10/13/2021 11:34:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Eventos](
	[IdEvento] [int] IDENTITY(1,1) NOT NULL,
	[IdCocinero] [int] NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
	[Fecha] [datetime] NOT NULL,
	[CantidadComensales] [int] NOT NULL,
	[Ubicacion] [nvarchar](50) NOT NULL,
	[Foto] [nvarchar](50) NOT NULL,
	[Precio] [decimal](18, 2) NOT NULL,
	[Estado] [int] NOT NULL,
 CONSTRAINT [PK_Eventos] PRIMARY KEY CLUSTERED 
(
	[IdEvento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EventosRecetas]    Script Date: 10/13/2021 11:34:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EventosRecetas](
	[IdEventoReceta] [int] IDENTITY(1,1) NOT NULL,
	[IdEvento] [int] NOT NULL,
	[IdReceta] [int] NOT NULL,
 CONSTRAINT [PK_EventosRecetas] PRIMARY KEY CLUSTERED 
(
	[IdEventoReceta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Recetas]    Script Date: 10/13/2021 11:34:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Recetas](
	[IdReceta] [int] IDENTITY(1,1) NOT NULL,
	[IdCocinero] [int] NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
	[TiempoCoccion] [int] NOT NULL,
	[Descripcion] [nvarchar](max) NOT NULL,
	[Ingredientes] [nvarchar](max) NOT NULL,
	[IdTipoReceta] [int] NOT NULL,
 CONSTRAINT [PK_Recetas] PRIMARY KEY CLUSTERED 
(
	[IdReceta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reservas]    Script Date: 10/13/2021 11:34:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reservas](
	[IdReserva] [int] IDENTITY(1,1) NOT NULL,
	[IdEvento] [int] NOT NULL,
	[IdComensal] [int] NOT NULL,
	[IdReceta] [int] NOT NULL,
	[CantidadComensales] [int] NOT NULL,
	[FechaCreacion] [datetime] NOT NULL,
 CONSTRAINT [PK_Reservas] PRIMARY KEY CLUSTERED 
(
	[IdReserva] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TipoRecetas]    Script Date: 10/13/2021 11:34:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TipoRecetas](
	[IdTipoReceta] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_TipoRecetas] PRIMARY KEY CLUSTERED 
(
	[IdTipoReceta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 10/13/2021 11:34:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[IdUsuario] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](60) NOT NULL,
	[Perfil] [int] NOT NULL,
	[FechaRegistracion] [datetime] NOT NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
	[IdUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Calificaciones]  WITH CHECK ADD  CONSTRAINT [FK_Calificaciones_Eventos] FOREIGN KEY([IdEvento])
REFERENCES [dbo].[Eventos] ([IdEvento])
GO
ALTER TABLE [dbo].[Calificaciones] CHECK CONSTRAINT [FK_Calificaciones_Eventos]
GO
ALTER TABLE [dbo].[Calificaciones]  WITH CHECK ADD  CONSTRAINT [FK_Calificaciones_Usuarios] FOREIGN KEY([IdComensal])
REFERENCES [dbo].[Usuarios] ([IdUsuario])
GO
ALTER TABLE [dbo].[Calificaciones] CHECK CONSTRAINT [FK_Calificaciones_Usuarios]
GO
ALTER TABLE [dbo].[Eventos]  WITH CHECK ADD  CONSTRAINT [FK_Eventos_Usuarios] FOREIGN KEY([IdCocinero])
REFERENCES [dbo].[Usuarios] ([IdUsuario])
GO
ALTER TABLE [dbo].[Eventos] CHECK CONSTRAINT [FK_Eventos_Usuarios]
GO
ALTER TABLE [dbo].[EventosRecetas]  WITH CHECK ADD  CONSTRAINT [FK_EventosRecetas_Eventos] FOREIGN KEY([IdEvento])
REFERENCES [dbo].[Eventos] ([IdEvento])
GO
ALTER TABLE [dbo].[EventosRecetas] CHECK CONSTRAINT [FK_EventosRecetas_Eventos]
GO
ALTER TABLE [dbo].[EventosRecetas]  WITH CHECK ADD  CONSTRAINT [FK_EventosRecetas_Recetas] FOREIGN KEY([IdReceta])
REFERENCES [dbo].[Recetas] ([IdReceta])
GO
ALTER TABLE [dbo].[EventosRecetas] CHECK CONSTRAINT [FK_EventosRecetas_Recetas]
GO
ALTER TABLE [dbo].[Recetas]  WITH CHECK ADD  CONSTRAINT [FK_Recetas_TipoRecetas] FOREIGN KEY([IdTipoReceta])
REFERENCES [dbo].[TipoRecetas] ([IdTipoReceta])
GO
ALTER TABLE [dbo].[Recetas] CHECK CONSTRAINT [FK_Recetas_TipoRecetas]
GO
ALTER TABLE [dbo].[Reservas]  WITH CHECK ADD  CONSTRAINT [FK_Reservas_Eventos] FOREIGN KEY([IdEvento])
REFERENCES [dbo].[Eventos] ([IdEvento])
GO
ALTER TABLE [dbo].[Reservas] CHECK CONSTRAINT [FK_Reservas_Eventos]
GO
ALTER TABLE [dbo].[Reservas]  WITH CHECK ADD  CONSTRAINT [FK_Reservas_Recetas] FOREIGN KEY([IdReceta])
REFERENCES [dbo].[Recetas] ([IdReceta])
GO
ALTER TABLE [dbo].[Reservas] CHECK CONSTRAINT [FK_Reservas_Recetas]
GO
ALTER TABLE [dbo].[Reservas]  WITH CHECK ADD  CONSTRAINT [FK_Reservas_Usuarios] FOREIGN KEY([IdComensal])
REFERENCES [dbo].[Usuarios] ([IdUsuario])
GO
ALTER TABLE [dbo].[Reservas] CHECK CONSTRAINT [FK_Reservas_Usuarios]
GO
USE [master]
GO
ALTER DATABASE [20212C_TP] SET  READ_WRITE 
GO
